name:                hs-orm
version:             0.1.0.0
github:              "githubuser/hs-orm"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hs-orm#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- time
- template-haskell
- transformers
- monad-control
- convertible
- aeson
- extensible
- profunctors
- comonad
- resource-pool
- HDBC
- HDBC-postgresql
- hs-graph
- hs-resource
- lens

library:
  source-dirs: src

executables:
  hs-orm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-orm

tests:
  hs-orm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hs-orm
